services:
  - type: web
    name: employee-management-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString
      - key: DEBUG
        value: false
      - key: UPLOAD_FOLDER
        value: uploads
      - key: MAX_FILE_SIZE
        value: 10485760

databases:
  - name: employee-db
    databaseName: employees
    user: employee_user
    plan: free
