name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f submission/requirements.txt ]; then pip install -r submission/requirements.txt; fi

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q || true

      - name: Security Scan (Bandit)
        run: |
          pip install bandit
          bandit -r submission -x tests || true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Render Deploy
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

